// Auto-generated by HARVEST agent_runner - do not edit.
//
// Post-compaction plan-file recovery for OpenCode runs. After a compaction
// the model's only fresh user input is OpenCode's generic synthetic
// "Continue if you have next steps..." message, with no explicit signal that
// a compaction happened; weak-instruction-following models resume straight
// from the summary's "Next Move" and never restore their plan files
// (observed in trace_zstd_44). This plugin puts the recovery instruction in
// the one place the model reliably obeys - the first user message after the
// compaction - and additionally shapes the summary itself.
//
// `{RECOVERY_CMD}` is substituted by agent_runner with the phase's recovery
// command (e.g. "cat PLAN.md"). Hook names verified byte-identical across
// opencode v1.17.19 (local) through v1.18.10/dev. Appends to
// `compaction_recovery.log` in the work dir so runs can verify the hooks
// actually fired.
import fs from "node:fs"

const RECOVERY_TEXT =
  "A context compaction just occurred: the conversation above was replaced " +
  "by a summary. FIRST ACTION (mandatory): run `{RECOVERY_CMD}` to restore " +
  "your working memory. Then continue with the next steps."

const logged = new Set()
function log(key, line) {
  if (logged.has(key)) return
  logged.add(key)
  try {
    fs.appendFileSync("compaction_recovery.log", new Date().toISOString() + " " + line + "\n")
  } catch {}
}

export const CompactionRecovery = async () => ({
  "experimental.session.compacting": async (_input, output) => {
    output.context.push(
      "The summary MUST end with a section titled 'MANDATORY FIRST ACTION' " +
        "stating: run `{RECOVERY_CMD}` before doing anything else.",
    )
    log("compacting:" + Date.now(), "compacting hook fired")
  },
  "experimental.chat.messages.transform": async (_input, output) => {
    for (const msg of output.messages) {
      if (msg.info.role !== "user") continue
      for (const part of msg.parts) {
        if (part.type !== "text" || typeof part.text !== "string") continue
        const marked = part.metadata && part.metadata.compaction_continue === true
        // Fallback for when the internal metadata marker changes upstream.
        const fallback =
          part.synthetic === true && part.text.startsWith("Continue if you have next steps")
        if (marked || fallback) {
          part.text = RECOVERY_TEXT
          log("rewrite:" + part.id, "rewrote compaction continue message " + part.id)
        }
      }
    }
  },
})
