# The default configurations options for harvest_translate.

force = false
log_filter = "info"
modular = false
stages = []
agentic_agent = "kiro"

[tools.raw_source_to_cargo_llm]
address = "http://localhost:11434"
backend = "ollama"
model = "codellama:7b"
max_tokens = 10000

[tools.modular_translation_llm]
address = "http://localhost:11434"
backend = "ollama"
model = "codellama:7b"
max_tokens = 10000

[tools.translate_agentic]

[tools.verify_fix_agentic]
